export type TMode = valueof<typeof modes>

export enum modes {
    START,
    // everything that is not inside filesection is NON_SECTIONED_CONTENT
    NON_SECTIONED_CONTENT_IN_PROGRESS,
    EXPECT_OPENING_BRACKET,
    EXPECT_FILESECTION_OPENING_TAGNAME,
    EXPECT_ATTRIBUTE,
    ATTRIBUTE_NAME_IN_PROGRESS,
    EXPECT_EQUAL_SIGN_BETWEEN_ATTRIBUTE_AND_VALUE,
    EXPECT_ATTRIBUTE_VALUE,
    QUOTTED_ATTRIBUTE_VALUE_IN_PROGRESS,
    UNQUOTTED_ATTRIBUTE_VALUE_IN_PROGRESS,
    FILESECTION_BODY_IN_PROGRESS,
}
